export type GeneratorConfig = {
  githubOwner: string;
  repoName: string;
  appName: string;
  bundleId: string;
  branch: string;
  visibility: "public" | "private";
  includeSigningNotes: boolean;
};

function escapeDoubleQuotes(value: string) {
  return value.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

function hereDoc(path: string, lines: string[]) {
  return [`cat > "${path}" <<'EOF'`, ...lines, "EOF", ""];
}

export const fallbackModelOrder = [
  "gemini-2.5-flash-lite",
  "gemini-2.5-flash",
  "gemini-2.5-pro",
];

export const generatedArtifacts = [
  "DMG для Intel Mac (x64)",
  "DMG для Apple Silicon Mac (arm64)",
  "Universal DMG",
  "Zip-артефакты для каждого macOS таргета",
];

export const githubSecrets = [
  {
    name: "APPLE_API_KEY",
    required: "Опционально",
    description: "Ключ App Store Connect для подписи и notarization через API key flow.",
  },
  {
    name: "APPLE_API_KEY_ID",
    required: "Опционально",
    description: "ID ключа App Store Connect.",
  },
  {
    name: "APPLE_API_ISSUER",
    required: "Опционально",
    description: "Issuer ID для notarization.",
  },
  {
    name: "CSC_LINK",
    required: "Опционально",
    description: "Base64/P12 сертификат Developer ID Application для подписанного DMG.",
  },
  {
    name: "CSC_KEY_PASSWORD",
    required: "Опционально",
    description: "Пароль к сертификату из CSC_LINK.",
  },
  {
    name: "GEMINI_API_KEY",
    required: "Не класть в GitHub secrets, вводить в приложении",
    description: "Ключ Gemini API пользователь вставляет в UI; приложение хранит его локально.",
  },
];

export function generateBootstrapScript(config: GeneratorConfig) {
  const owner = escapeDoubleQuotes(config.githubOwner.trim() || "your-github-user");
  const repo = escapeDoubleQuotes(config.repoName.trim() || "floorplan-ai-electron");
  const appName = escapeDoubleQuotes(config.appName.trim() || "Floorplan AI Studio");
  const bundleId = escapeDoubleQuotes(config.bundleId.trim() || "com.example.floorplanai");
  const branch = escapeDoubleQuotes(config.branch.trim() || "main");
  const visibilityFlag = config.visibility === "private" ? "--private" : "--public";

  const lines: string[] = [
    "#!/usr/bin/env bash",
    "set -euo pipefail",
    "",
    "# ------------------------------------------------------------",
    "# Floorplan AI Electron bootstrap for macOS",
    "# What it does:",
    "# 1) checks/install Xcode CLT, Homebrew, GitHub CLI, Node.js",
    "# 2) creates Electron + React + Vite repo",
    "# 3) pushes it to GitHub",
    "# 4) adds GitHub Actions for x64 / arm64 / universal DMG builds",
    "# 5) writes docs about Gemini model probing, fallback and signing",
    "# ------------------------------------------------------------",
    "",
    `GITHUB_OWNER=\"${owner}\"`,
    `REPO_NAME=\"${repo}\"`,
    `APP_NAME=\"${appName}\"`,
    `BUNDLE_ID=\"${bundleId}\"`,
    `DEFAULT_BRANCH=\"${branch}\"`,
    "NODE_VERSION=\"22\"",
    "WORKDIR=\"$HOME/Desktop/${REPO_NAME}\"",
    `GH_VISIBILITY=\"${visibilityFlag}\"`,
    "",
    "log() { printf '\n[%s] %s\n' \"$(date '+%H:%M:%S')\" \"$1\"; }",
    "fail() { echo \"ERROR: $1\" >&2; exit 1; }",
    "has() { command -v \"$1\" >/dev/null 2>&1; }",
    "",
    "[[ \"$(uname -s)\" == \"Darwin\" ]] || fail \"Этот скрипт рассчитан только на macOS.\"",
    "",
    "ensure_xcode_clt() {",
    "  if xcode-select -p >/dev/null 2>&1; then",
    "    log \"Xcode Command Line Tools уже установлены\"",
    "    return 0",
    "  fi",
    "",
    "  log \"Устанавливаю Xcode Command Line Tools\"",
    "  xcode-select --install || true",
    "  until xcode-select -p >/dev/null 2>&1; do",
    "    sleep 20",
    "    log \"Жду завершения установки Xcode Command Line Tools...\"",
    "  done",
    "}",
    "",
    "ensure_homebrew() {",
    "  if has brew; then",
    "    log \"Homebrew уже установлен\"",
    "    return 0",
    "  fi",
    "",
    "  log \"Устанавливаю Homebrew\"",
    "  NONINTERACTIVE=1 /bin/bash -c \"$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)\"",
    "  if [[ -x /opt/homebrew/bin/brew ]]; then",
    "    eval \"$(/opt/homebrew/bin/brew shellenv)\"",
    "  elif [[ -x /usr/local/bin/brew ]]; then",
    "    eval \"$(/usr/local/bin/brew shellenv)\"",
    "  fi",
    "}",
    "",
    "ensure_brew_package() {",
    "  local binary=\"$1\"",
    "  local formula=\"$2\"",
    "  if has \"$binary\"; then",
    "    log \"$binary уже доступен\"",
    "    return 0",
    "  fi",
    "  log \"Устанавливаю $formula\"",
    "  brew install \"$formula\"",
    "}",
    "",
    "ensure_gh_auth() {",
    "  if gh auth status >/dev/null 2>&1; then",
    "    log \"GitHub CLI уже авторизован\"",
    "    return 0",
    "  fi",
    "  log \"Нужна авторизация GitHub CLI. Откроется браузер.\"",
    "  gh auth login -w -s repo,workflow,read:org",
    "}",
    "",
    "write_common_docs() {",
    "  mkdir -p docs build .github/workflows",
    "}",
    "",
    "bootstrap_repo() {",
    "  rm -rf \"$WORKDIR\"",
    "  mkdir -p \"$(dirname \"$WORKDIR\")\"",
    "  cd \"$(dirname \"$WORKDIR\")\"",
    "",
    "  log \"Создаю Electron + React + TypeScript scaffold\"",
    "  npm create @quick-start/electron@latest \"$REPO_NAME\" -- --template react-ts",
    "  cd \"$WORKDIR\"",
    "",
    "  log \"Ставлю зависимости проекта\"",
    "  npm install",
    "  npm install electron-builder zod",
    "",
    "  write_common_docs",
    "}",
    "",
    "patch_package_json() {",
    "  log \"Патчу package.json под DMG-сборки и GitHub Releases\"",
    "  export REPO_NAME APP_NAME BUNDLE_ID",
    "  node <<'NODE'",
    "const fs = require('fs');",
    "const pkg = JSON.parse(fs.readFileSync('package.json', 'utf8'));",
    "pkg.name = process.env.REPO_NAME;",
    "pkg.productName = process.env.APP_NAME;",
    "pkg.description = 'Electron app for Gemini-powered floorplan room segmentation and export';",
    "pkg.author = pkg.author || 'Bootstrap generated locally';",
    "pkg.license = pkg.license || 'MIT';",
    "pkg.scripts = {",
    "  ...(pkg.scripts || {}),",
    "  'dist:mac:x64': 'npm run build && electron-builder --mac dmg zip --x64 --config electron-builder.yml',",
    "  'dist:mac:arm64': 'npm run build && electron-builder --mac dmg zip --arm64 --config electron-builder.yml',",
    "  'dist:mac:universal': 'npm run build && electron-builder --mac dmg zip --universal --config electron-builder.yml'",
    "};",
    "fs.writeFileSync('package.json', JSON.stringify(pkg, null, 2) + '\\n');",
    "NODE",
    "}",
    "",
  ];

  lines.push(
    ...hereDoc("electron-builder.yml", [
      `appId: ${bundleId}`,
      `productName: ${appName}`,
      "directories:",
      "  buildResources: build",
      "files:",
      "  - out/**",
      "  - package.json",
      "mac:",
      "  category: public.app-category.graphics-design",
      "  artifactName: \"${productName}-${version}-${arch}.${ext}\"",
      "  identity: null",
      "  notarize: false",
      "  hardenedRuntime: false",
      "  gatekeeperAssess: false",
      "  target:",
      "    - target: dmg",
      "      arch:",
      "        - x64",
      "        - arm64",
      "        - universal",
      "    - target: zip",
      "      arch:",
      "        - x64",
      "        - arm64",
      "        - universal",
      "dmg:",
      "  sign: false",
      "publish:",
      "  provider: github",
      "  releaseType: release",
    ]),
  );

  lines.push(
    ...hereDoc("build/entitlements.mac.plist", [
      "<?xml version=\"1.0\" encoding=\"UTF-8\"?>",
      "<!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">",
      "<plist version=\"1.0\">",
      "  <dict>",
      "    <key>com.apple.security.cs.allow-jit</key>",
      "    <true/>",
      "    <key>com.apple.security.cs.allow-unsigned-executable-memory</key>",
      "    <true/>",
      "    <key>com.apple.security.cs.disable-library-validation</key>",
      "    <true/>",
      "  </dict>",
      "</plist>",
    ]),
  );

  lines.push(
    ...hereDoc("build/entitlements.mac.inherit.plist", [
      "<?xml version=\"1.0\" encoding=\"UTF-8\"?>",
      "<!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">",
      "<plist version=\"1.0\">",
      "  <dict>",
      "    <key>com.apple.security.cs.allow-jit</key>",
      "    <true/>",
      "    <key>com.apple.security.cs.allow-unsigned-executable-memory</key>",
      "    <true/>",
      "    <key>com.apple.security.cs.disable-library-validation</key>",
      "    <true/>",
      "  </dict>",
      "</plist>",
    ]),
  );

  lines.push(
    ...hereDoc(".env.example", [
      "# Пользовательский ключ Gemini лучше хранить локально в приложении, а не в репозитории.",
      "GEMINI_API_KEY=",
      "",
      "# Дальше — опциональные переменные для подписанных и notarized macOS сборок.",
      "APPLE_API_KEY=",
      "APPLE_API_KEY_ID=",
      "APPLE_API_ISSUER=",
      "CSC_LINK=",
      "CSC_KEY_PASSWORD=",
    ]),
  );

  lines.push(
    ...hereDoc("docs/SPEC.md", [
      `# ${appName} — product spec`,
      "",
      "## Пользовательский сценарий",
      "1. Пользователь загружает планировку.",
      "2. Приложение отправляет её в Gemini API с инструкцией: выделить каждое помещение уникальным цветом.",
      "3. Возвращённая маска/изображение анализируется локально.",
      "4. Приложение строит полигоны по цветовым областям.",
      "5. Пользователь видит список помещений и чекбоксами выбирает нужные.",
      "6. Выбранные помещения экспортируются в папку, которую выберет пользователь.",
      "7. В приложении есть поле для Gemini API key и отдельная кнопка открытия логов.",
      "",
      "## Обязательные блоки UI",
      "- Ввод API key",
      "- Проверка доступных моделей по `GET /v1beta/models`",
      "- Выделение моделей, которые стоит пробовать первыми на free tier",
      "- Fallback на следующую модель при 4xx/5xx/429 ошибке",
      "- Загрузка плана",
      "- Просмотр исходного изображения",
      "- Просмотр цветной маски",
      "- Просмотр построенных полигонов",
      "- Чекбоксы по помещениям",
      "- Экспорт выбранных помещений",
      "- Журнал событий / ошибок",
      "",
      "## Важное ограничение",
      "Gemini Developer API позволяет листать модели, но публичного стабильного REST-метода для получения точного остатка free-tier quota по модели нет. Поэтому приложение должно:",
      "- хранить предпочтительный порядок моделей,",
      "- делать лёгкий probe-запрос,",
      "- перехватывать 429 / quota errors,",
      "- переключаться на следующую модель,",
      "- показывать пользователю честный статус, а не обещать точный остаток лимита.",
    ]),
  );

  lines.push(
    ...hereDoc("docs/GEMINI_NOTES.md", [
      "# Gemini integration notes",
      "",
      "## Official endpoints to use",
      "- List models: `GET https://generativelanguage.googleapis.com/v1beta/models`",
      "- Header auth: `x-goog-api-key: <KEY>`",
      "- Generate content: `POST /v1beta/models/{model}:generateContent`",
      "",
      "## Recommended fallback order",
      ...fallbackModelOrder.map((model, index) => `${index + 1}. ${model}`),
      "",
      "## Honest quota handling",
      "The public Gemini docs expose pricing, tiers and model listing. They do not expose a simple public endpoint for 'remaining free requests today for this exact model'.",
      "So the app should combine:",
      "- model listing from the API,",
      "- curated preferred order based on pricing/free-tier availability,",
      "- tiny probe calls,",
      "- runtime fallback after API errors.",
      "",
      "## Prompting recommendation",
      "For the room-segmentation workflow, ask Gemini for BOTH:",
      "1. a flat color mask / color-coded room output, and",
      "2. a structured room manifest JSON with color-to-room mapping.",
      "The JSON manifest makes polygon attribution much more reliable than trying to infer semantics from colors alone.",
    ]),
  );

  lines.push(
    ...hereDoc("docs/ARCHITECTURE.md", [
      `# ${appName} architecture`,
      "",
      "## Renderer responsibilities",
      "- API key input and local secure persistence",
      "- Floorplan upload and preview",
      "- Model discovery UI",
      "- Polygon overlay preview",
      "- Room selection and export commands",
      "- Log viewer drawer or modal",
      "",
      "## Main process responsibilities",
      "- Native open/save dialogs",
      "- Log file persistence",
      "- Export selected rooms to user-selected folder",
      "- Safe file system access through preload bridge",
      "",
      "## Recommended module split",
      "- `src/features/api-key`",
      "- `src/features/model-discovery`",
      "- `src/features/floorplan-upload`",
      "- `src/features/mask-to-polygons`",
      "- `src/features/export`",
      "- `src/features/logs`",
      "",
      "## Export formats",
      "Suggested output set:",
      "- room polygons as JSON",
      "- room mask snippets as PNG",
      "- optional SVG overlay",
      "- export manifest with room name, color and polygon coordinates",
    ]),
  );

  lines.push(
    ...hereDoc("docs/GITHUB_SECRETS.md", [
      "# GitHub secrets for macOS signing",
      "",
      "Unsigned DMG can be built immediately. Signed + notarized DMG needs Apple credentials.",
      "",
      "## Recommended secrets",
      "- `APPLE_API_KEY`",
      "- `APPLE_API_KEY_ID`",
      "- `APPLE_API_ISSUER`",
      "- `CSC_LINK`",
      "- `CSC_KEY_PASSWORD`",
      "",
      "## Important",
      "This bootstrap intentionally ships unsigned builds first (`identity: null`).",
      "When you are ready for production notarization, remove `identity: null` and `notarize: false` from `electron-builder.yml`, then add the Apple secrets above.",
      config.includeSigningNotes
        ? ""
        : "# Signing notes are intentionally minimized because the current generator is configured for unsigned bootstrap first.",
    ].filter(Boolean)),
  );

  lines.push(
    ...hereDoc(".github/workflows/release.yml", [
      "name: release-macos",
      "",
      "on:",
      "  workflow_dispatch:",
      "  push:",
      "    tags:",
      "      - 'v*'",
      "",
      "permissions:",
      "  contents: write",
      "",
      "jobs:",
      "  build:",
      "    strategy:",
      "      fail-fast: false",
      "      matrix:",
      "        include:",
      "          - runner: macos-15-intel",
      "            target: mac-x64",
      "            script: dist:mac:x64",
      "          - runner: macos-latest",
      "            target: mac-arm64",
      "            script: dist:mac:arm64",
      "          - runner: macos-latest",
      "            target: mac-universal",
      "            script: dist:mac:universal",
      "",
      "    runs-on: ${{ matrix.runner }}",
      "",
      "    env:",
      "      CSC_IDENTITY_AUTO_DISCOVERY: false",
      "",
      "    steps:",
      "      - name: Checkout",
      "        uses: actions/checkout@v4",
      "",
      "      - name: Setup Node",
      "        uses: actions/setup-node@v4",
      "        with:",
      "          node-version: 22",
      "          cache: npm",
      "",
      "      - name: Install dependencies",
      "        run: npm ci",
      "",
      "      - name: Build ${appName}",
      "        run: npm run ${{ matrix.script }}",
      "",
      "      - name: Upload DMG artifacts",
      "        uses: actions/upload-artifact@v4",
      "        with:",
      "          name: ${{ matrix.target }}",
      "          path: |",
      "            dist/*.dmg",
      "            dist/*.zip",
      "",
      "      - name: Publish to GitHub Release on tags",
      "        if: startsWith(github.ref, 'refs/tags/v')",
      "        uses: softprops/action-gh-release@v2",
      "        with:",
      "          files: |",
      "            dist/*.dmg",
      "            dist/*.zip",
    ]),
  );

  lines.push(
    ...hereDoc("README.md", [
      `# ${appName}`,
      "",
      "Electron + React + Vite bootstrap for a macOS floorplan segmentation app using Gemini API.",
      "",
      "## What this repository includes",
      "- Electron desktop shell",
      "- React renderer scaffold",
      "- GitHub Actions for x64 / arm64 / universal DMG builds",
      "- docs for Gemini model discovery, fallback, export and signing",
      "- unsigned packaging path that works before Apple notarization is configured",
      "",
      "## Quick commands",
      "```bash",
      "npm install",
      "npm run dev",
      "npm run dist:mac:x64",
      "npm run dist:mac:arm64",
      "npm run dist:mac:universal",
      "```",
      "",
      "## Where to continue next",
      "1. Implement Gemini model discovery UI via `GET /v1beta/models`.",
      "2. Add room color mask request + JSON room manifest.",
      "3. Implement mask-to-polygon extraction in renderer worker or utility module.",
      "4. Bridge export and logging through Electron preload.",
      "5. Add Apple signing secrets when you need notarized DMG.",
    ]),
  );

  lines.push(
    "create_git_repo() {",
    "  log \"Инициализирую git и пушу в GitHub\"",
    "  git init",
    "  git add .",
    "  git commit -m \"chore: bootstrap electron floorplan app\"",
    "  git branch -M \"$DEFAULT_BRANCH\"",
    "",
    "  if gh repo view \"$GITHUB_OWNER/$REPO_NAME\" >/dev/null 2>&1; then",
    "    log \"Репозиторий уже существует, просто привязываю origin\"",
    "    git remote remove origin >/dev/null 2>&1 || true",
    "    git remote add origin \"https://github.com/$GITHUB_OWNER/$REPO_NAME.git\"",
    "    git push -u origin \"$DEFAULT_BRANCH\" --force-with-lease",
    "  else",
    "    gh repo create \"$GITHUB_OWNER/$REPO_NAME\" $GH_VISIBILITY --source=. --remote=origin --push",
    "  fi",
    "}",
    "",
    "print_next_steps() {",
    "  cat <<TXT",
    "",
    "Готово.",
    "",
    "Что создано:",
    "- локальная папка: $WORKDIR",
    "- GitHub repo: https://github.com/$GITHUB_OWNER/$REPO_NAME",
    "- workflow: .github/workflows/release.yml",
    "- unsigned DMG pipeline для x64 / arm64 / universal",
    "",
    "Что делать дальше:",
    "1) Открой проект: cd \"$WORKDIR\"",
    "2) Запусти dev-режим: npm run dev",
    "3) Когда будешь готов к CI release, создай тег: git tag v0.1.0 && git push origin v0.1.0",
    "4) Если нужен notarized DMG без предупреждений Gatekeeper — добавь Apple secrets и включи signing",
    "",
    "TXT",
    "}",
    "",
    "main() {",
    "  ensure_xcode_clt",
    "  ensure_homebrew",
    "  ensure_brew_package git git",
    "  ensure_brew_package gh gh",
    "  ensure_brew_package node node@22",
    "  ensure_gh_auth",
    "  bootstrap_repo",
    "  patch_package_json",
    "  create_git_repo",
    "  print_next_steps",
    "}",
    "",
    "main \"$@\"",
  );

  return lines.join("\n");
}
